# Generated by Django 2.2 on 2021-08-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210809_1908'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='product',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
